name: bodah
description: "Bodah App"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.13.1
  pdf: ^3.10.8
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0+1
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.9.0
  url_launcher: ^6.2.5
  intl: any
  flutter_localization: any
  table_calendar: ^3.0.9
  intl_phone_field: ^3.2.0
  fl_chart: ^0.66.2
  carousel_slider: ^4.0.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.0.6 
  flutter_secure_storage: ^9.2.2
  http: ^1.2.1
  
  flutter_localizations:
    sdk: flutter
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  animated_splash_screen: ^1.3.0
  mailer: ^6.1.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  math_expressions: ^2.0.0
  dropdown_search: ^5.0.6
  flutter_iconpicker_plus: ^3.2.3
  dotted_border: ^2.0.0
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
 
 
  uses-material-design: true
  assets:
     - images/
     - fonts/
flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

